[package]
name = "Skills Module"
description = "A framework for adding custom skills."
homepage = "https://www.nexusmods.com/morrowind/mods/46034"
repository = "https://github.com/jhaakma/SkillsModule"
authors = [ "Merlord",]
version = "2.0.3"

[dependencies]
assets = [ "MWSE/lib/OtherSkills", "Icons/otherskills",]

[dependencies.mwse]
buildnumber = 3251

[dependencies.mge-xe]
version = ">=0.15.0"